const products = [
    {
        id: 1,
        name: "ASUS ZenBook Pro 14 Duo",
        category: "Laptops",
        price: 159999,
        originalPrice: 179999,
        rating: 4.8,
        reviews: 124,
        image: "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?q=80&w=600&auto=format&fit=crop",
        description: "Dual-screen laptop with high-performance specs for creators and pros.",
        specs: { "Processor": "i9-13900H", "RAM": "32GB", "Storage": "1TB SSD", "GPU": "RTX 4060" },
        brand: "ASUS",
        stock: 15, trending: true, featured: true
    },
    {
        id: 2,
        name: "iPhone 15 Pro Max",
        category: "Smartphones",
        price: 148900,
        originalPrice: 159900,
        rating: 4.9,
        reviews: 856,
        image: "https://images.unsplash.com/photo-1695048133142-1a20484d2569?q=80&w=600&auto=format&fit=crop",
        description: "The ultimate iPhone with Titanium design and Pro camera system.",
        specs: { "Processor": "A17 Pro", "RAM": "8GB", "Storage": "256GB", "Display": "6.7\" OLED" },
        brand: "Apple",
        stock: 25, trending: true, featured: true
    },
    {
        id: 3,
        name: "Sony WH-1000XM5",
        category: "Headphones",
        price: 29990,
        originalPrice: 34990,
        rating: 4.7,
        reviews: 2150,
        image: "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?q=80&w=600&auto=format&fit=crop",
        description: "Industry-leading noise cancelling headphones with exceptional sound.",
        specs: { "Type": "Over-ear", "Battery": "30h", "Connectivity": "Bluetooth 5.2" },
        brand: "Sony",
        stock: 50, trending: true, featured: false
    },
    {
        id: 9,
        name: "HP Spectre x360",
        category: "Laptops",
        price: 115000,
        originalPrice: 135000,
        rating: 4.7,
        reviews: 88,
        image: "https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?q=80&w=600&auto=format&fit=crop",
        description: "Elegant 2-in-1 laptop with stunning display and all-day battery life.",
        specs: { "Processor": "i7-1355U", "RAM": "16GB", "Storage": "512GB SSD", "Display": "4K OLED" },
        brand: "HP",
        stock: 12, trending: true, featured: true
    },
    {
        id: 10,
        name: "Dell XPS 13 Plus",
        category: "Laptops",
        price: 165000,
        originalPrice: 180000,
        rating: 4.8,
        reviews: 56,
        image: "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?q=80&w=600&auto=format&fit=crop",
        description: "Modern, minimalist design with powerful performance.",
        specs: { "Processor": "i7-1360P", "RAM": "32GB", "Storage": "1TB SSD", "Display": "3.5K OLED" },
        brand: "Dell",
        stock: 8, trending: false, featured: true
    },
    {
        id: 11,
        name: "Lenovo Legion 5 Pro",
        category: "Laptops",
        price: 135000,
        originalPrice: 155000,
        rating: 4.9,
        reviews: 210,
        image: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?q=80&w=600&auto=format&fit=crop",
        description: "Powerful gaming laptop with high-refresh-rate display.",
        specs: { "Processor": "Ryzen 7", "RAM": "16GB", "GPU": "RTX 4070", "Display": "165Hz" },
        brand: "Lenovo",
        stock: 10, trending: true, featured: false
    },
    {
        id: 12,
        name: "Vivo V29 Pro",
        category: "Smartphones",
        price: 39999,
        originalPrice: 44999,
        rating: 4.5,
        reviews: 320,
        image: "https://images.unsplash.com/photo-1678911820864-e2c567c655d7?q=80&w=600&auto=format&fit=crop",
        description: "Sleek smartphone with professional aura light portrait capabilities.",
        specs: { "RAM": "12GB", "Storage": "256GB", "Battery": "4600mAh", "Camera": "50MP OIS" },
        brand: "Vivo",
        stock: 45, trending: true, featured: false
    },
    {
        id: 13,
        name: "Oppo Reno 10 Pro+",
        category: "Smartphones",
        price: 54999,
        originalPrice: 59999,
        rating: 4.6,
        reviews: 180,
        image: "https://images.unsplash.com/photo-1580910051074-3eb694886505?q=80&w=600&auto=format&fit=crop",
        description: "The portrait expert with 64MP telephoto lens.",
        specs: { "RAM": "12GB", "Storage": "256GB", "SoC": "Snapdragon 8+ Gen 1" },
        brand: "Oppo",
        stock: 30, trending: false, featured: true
    },
    {
        id: 14,
        name: "Realme GT 5G",
        category: "Smartphones",
        price: 35999,
        originalPrice: 39999,
        rating: 4.4,
        reviews: 450,
        image: "https://images.unsplash.com/photo-1616348436168-de43ad0db179?q=80&w=600&auto=format&fit=crop",
        description: "Flagship killer with ultra-fast charging and high refresh rate screen.",
        specs: { "RAM": "8GB", "Storage": "128GB", "Charging": "65W Dart", "Display": "120Hz AMOLED" },
        brand: "Realme",
        stock: 60, trending: true, featured: false
    },
    {
        id: 15,
        name: "PlayStation 5 Console",
        category: "Gaming",
        price: 54990,
        originalPrice: 59990,
        rating: 4.9,
        reviews: 5400,
        image: "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?q=80&w=600&auto=format&fit=crop",
        description: "Next-gen gaming experience with lightning-fast loading and 4K support.",
        specs: { "GPU": "10.3 TFLOPS", "SSD": "825GB Custom", "Feature": "Ray Tracing" },
        brand: "Sony",
        stock: 5, trending: true, featured: true
    },
    {
        id: 16,
        name: "DualSense Edge Controller",
        category: "Accessories",
        price: 18990,
        originalPrice: 19990,
        rating: 4.8,
        reviews: 120,
        image: "https://images.unsplash.com/photo-1612287230202-1ff1d85d1bdf?q=80&w=600&auto=format&fit=crop",
        description: "Pro-level controller with customizable buttons and triggers.",
        specs: { "Connectivity": "USB-C/BT", "Switches": "Replaceable sticks" },
        brand: "Sony",
        stock: 20, trending: true, featured: false
    }
];

const categories = ["All", "Laptops", "Smartphones", "Headphones", "Gaming", "Accessories"];

export { products, categories };
